-- Para criar um usuario e dar a permissão de SYSDBA

-- CRIAR USUARIO (ESQUEMA)
CREATE USER IDYL
IDENTIFIED BY IDYL3737
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP


-- CRIAR TABLE
CREATE TABLE TB_FORNECEDOR(
CD_FORNECEDOR NUMBER(5) PRIMARY KEY NOT NULL,
NM_CONTATO VARCHAR(50) NOT NULL,
DT_CADASTRO DATE DEFAULT SYSDATE NOT NULL
);

-- CRIAR SEQUENCE
CREATE SEQUENCE SQ_FORNECEDOR
START WITH 1
INCREMENT BY 1 

-- ADD FORNECEDOR

INSERT INTO TB_FORNECEDOR ( CD_FORNECEDOR, NM_CONTATO)
VALUES(SQ_FORNECEDOR.NEXTVAL,
'IDYL ICARO');

-- RESULTADO
SELECT * FROM TB_FORNECEDOR;

CD_FORNECEDOR NM_CONTATO                                         DT_CADAS
------------- -------------------------------------------------- --------
            1 IDYL ICARO                                         26/07/22